export default [
  "",
  {
    title: "基础与工程",
    collapsable: true,
    children: [
      "./基础特性/Flutter_目录结构.md",
      "./基础特性/Flutter_组件.md",
      "./基础特性/Flutter_有状态无状态组件.md",
      "./基础特性/Flutter_生命周期.md",
      "./基础特性/Flutter_调试工具.md",
      "./搞七捻三/Flutter_gradle编译加速.md",
    ],
  },
  {
    title: "约束与布局",
    collapsable: true,
    children: [
      "./基础特性/Flutter_布局约束规则.md",
      "./基础特性/Flutter_松约束.md",
      "./基础特性/Flutter_紧约束.md",
      "./基础特性/Flutter_无边界.md",
      "./容器布局/Flutter_盒模型.md",
      "./容器布局/Flutter_容器.md",
      "./容器布局/Flutter_线性布局.md",
      "./容器布局/Flutter_弹性布局.md",
      "./容器布局/Flutter_流式布局.md",
      "./容器布局/Flutter_层叠布局.md",
      "./容器布局/Flutter_对齐组件.md",
    ],
  },
  {
    title: "常用组件",
    collapsable: true,
    children: [
      "./常用组件/Flutter_文本组件.md",
      "./常用组件/Flutter_图片组件.md",
      "./常用组件/Flutter_图标组件.md",
      "./常用组件/Flutter_按钮组件.md",
      "./常用组件/Flutter_输入框.md",
      "./常用组件/Flutter_手势识别.md",
    ],
  },
  {
    title: "应用结构与配置",
    collapsable: true,
    children: [
      "./容器布局/Flutter_MaterialApp.md",
      "./容器布局/Flutter_脚手架.md",
      "./常用组件/Flutter_路由管理.md",
      "./常用组件/Flutter_导入资源.md",
      "./常用组件/Flutter_样式管理.md",
    ],
  },
];
